name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDY4YWYyOTItMTYwZC00Yzg5LTk4NDMtYzNlNDczOGU0OTVhIiwidGVuYW50X2lkIjoiOGRlZmQ3NGZmNDk2NDIxNTg1ZjA1N2IyZTRiNmIwNDFmODEzOWY2ZThmYzE2MzAzNzE4MTIyMWYwMjJiZDBhZCIsImludGVybmFsX3NlY3JldCI6IjRlZmE1MWI2LTZjNWItNGJhYS04NjU2LWY2NjhhYmI2ZGM2NiJ9.F-54YwJ5M8BEqkP0Jr9JULvv4yrTmlP2ybS_OZfpBGk"
JWT_SECRET="123455"